export { default as componentSetting } from './src/componentSetting'
export * from './src/designSetting'
export * from './src/encryptionSetting'
export * from './src/localeSetting'
// export * from './src/projectSetting'
