export default {
  success: true,
  code: '0000',
  data: [
    {
      id: 1,
      name: '大西科',
      parentId: 0,
      children: [
        {
          id: 109,
          name: '西科控股',
          parentId: 1,
          children: [
            {
              id: 111,
              name: '总经理办公室',
              parentId: 109,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 0.0,
              enabled: 1,
            },
            {
              id: 115,
              name: '运营服务部',
              parentId: 109,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 0.0,
              enabled: 1,
            },
            {
              id: 117,
              name: '政策研究室',
              parentId: 109,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 0.0,
              enabled: 1,
            },
            {
              id: 118,
              name: '品牌部',
              parentId: 109,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 0.0,
              enabled: 1,
            },
            {
              id: 136,
              name: '科技金融组',
              parentId: 109,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 0.0,
              enabled: 1,
            },
            {
              id: 156,
              name: '追光硬科技',
              parentId: 109,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 0.0,
              enabled: 1,
            },
            {
              id: 116,
              name: '企业管理部',
              parentId: 109,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 0.1,
              enabled: 1,
            },
            {
              id: 110,
              name: '人力资源部',
              parentId: 109,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 2.0,
              enabled: 1,
            },
            {
              id: 112,
              name: '财务部',
              parentId: 109,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 3.0,
              enabled: 1,
            },
            {
              id: 113,
              name: '数字信息部',
              parentId: 109,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 5.0,
              enabled: 1,
            },
            {
              id: 114,
              name: '资产管理部',
              parentId: 109,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 6.0,
              enabled: 1,
            },
            {
              id: 134,
              name: '硬科技战略研究部',
              parentId: 109,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 10.0,
              enabled: 1,
            },
            {
              id: 135,
              name: '众创空间',
              parentId: 109,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 11.0,
              enabled: 1,
            },
          ],
          expanded: false,
          leaf: false,
          checked: null,
          level: 2,
          seq: 0.0,
          enabled: 1,
        },
        {
          id: 3,
          name: '中科创星',
          parentId: 1,
          children: [
            {
              id: 56,
              name: 'CEO办公室',
              parentId: 3,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 0.0,
              enabled: 1,
            },
            {
              id: 61,
              name: '投资部',
              parentId: 3,
              children: [
                {
                  id: 126,
                  name: '军工组',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 1.0,
                  enabled: 1,
                },
                {
                  id: 66,
                  name: '先进制造组',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 2.0,
                  enabled: 1,
                },
                {
                  id: 67,
                  name: '新能源组',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 3.0,
                  enabled: 1,
                },
                {
                  id: 64,
                  name: '光电组',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 4.0,
                  enabled: 1,
                },
                {
                  id: 63,
                  name: '半导体组',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 5.0,
                  enabled: 1,
                },
                {
                  id: 65,
                  name: '激光组',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 6.0,
                  enabled: 1,
                },
                {
                  id: 68,
                  name: '医疗组',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 7.0,
                  enabled: 1,
                },
                {
                  id: 127,
                  name: '院地合作',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 8.0,
                  enabled: 1,
                },
                {
                  id: 133,
                  name: '前沿科技组',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 9.0,
                  enabled: 1,
                },
                {
                  id: 128,
                  name: '合伙人组',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 10.0,
                  enabled: 1,
                },
                {
                  id: 143,
                  name: '行研组',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 10.0,
                  enabled: 1,
                },
                {
                  id: 129,
                  name: '专项基金',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 10.1,
                  enabled: 1,
                },
                {
                  id: 131,
                  name: '其他',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 11.0,
                  enabled: 1,
                },
                {
                  id: 151,
                  name: '新材料组',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 11.0,
                  enabled: 1,
                },
                {
                  id: 124,
                  name: '大数据组（历史小组）',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 12.0,
                  enabled: 0,
                },
                {
                  id: 62,
                  name: '军民融合组（历史）',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 13.0,
                  enabled: 0,
                },
                {
                  id: 125,
                  name: '智能物联网组（历史小组）',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 13.0,
                  enabled: 0,
                },
                {
                  id: 130,
                  name: '个人管理（历史小组）',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 18.0,
                  enabled: 0,
                },
                {
                  id: 123,
                  name: '公司管理（特殊分组）',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 20.0,
                  enabled: 1,
                },
                {
                  id: 132,
                  name: '成长基金组（历史小组）',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 20.0,
                  enabled: 0,
                },
                {
                  id: 122,
                  name: '人工智能组（历史小组）',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 21.0,
                  enabled: 0,
                },
                {
                  id: 121,
                  name: '先导光电组（历史小组）',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 22.0,
                  enabled: 0,
                },
                {
                  id: 69,
                  name: '智能物联网组（历史）',
                  parentId: 61,
                  children: [],
                  expanded: false,
                  leaf: true,
                  checked: null,
                  level: 4,
                  seq: 24.0,
                  enabled: 0,
                },
              ],
              expanded: false,
              leaf: false,
              checked: null,
              level: 3,
              seq: 1.0,
              enabled: 1,
            },
            {
              id: 57,
              name: '产业发展部',
              parentId: 3,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 2.0,
              enabled: 1,
            },
            {
              id: 58,
              name: '资产管理部',
              parentId: 3,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 3.0,
              enabled: 1,
            },
            {
              id: 59,
              name: '合规风控部',
              parentId: 3,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 4.0,
              enabled: 1,
            },
            {
              id: 60,
              name: '品牌部',
              parentId: 3,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 5.0,
              enabled: 1,
            },
            {
              id: 70,
              name: '投资者关系管理部',
              parentId: 3,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 7.0,
              enabled: 1,
            },
            {
              id: 71,
              name: '行研部',
              parentId: 3,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 8.0,
              enabled: 1,
            },
            {
              id: 72,
              name: '院地合作部',
              parentId: 3,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 9.0,
              enabled: 1,
            },
            {
              id: 73,
              name: '政府资源部',
              parentId: 3,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 10.0,
              enabled: 1,
            },
            {
              id: 74,
              name: '综合部',
              parentId: 3,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 11.0,
              enabled: 1,
            },
            {
              id: 75,
              name: '人力资源部',
              parentId: 3,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 12.0,
              enabled: 1,
            },
            {
              id: 76,
              name: '财务部',
              parentId: 3,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 13.0,
              enabled: 1,
            },
            {
              id: 77,
              name: '运营部',
              parentId: 3,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 14.0,
              enabled: 1,
            },
            {
              id: 150,
              name: '科服投行部',
              parentId: 3,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 15.0,
              enabled: 1,
            },
          ],
          expanded: false,
          leaf: false,
          checked: null,
          level: 2,
          seq: 1.0,
          enabled: 1,
        },
        {
          id: 85,
          name: '星创科服',
          parentId: 1,
          children: [
            {
              id: 87,
              name: '总经办',
              parentId: 85,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 4,
              seq: 1.0,
              enabled: 1,
            },
            {
              id: 120,
              name: '产业发展组',
              parentId: 85,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 4,
              seq: 6.0,
              enabled: 1,
            },
            {
              id: 148,
              name: '咨询服务部',
              parentId: 85,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 4,
              seq: 9.0,
              enabled: 1,
            },
            {
              id: 88,
              name: '客户及运营组',
              parentId: 85,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 4,
              seq: 11.0,
              enabled: 1,
            },
            {
              id: 152,
              name: '战略资源组',
              parentId: 85,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 4,
              seq: 12.0,
              enabled: 1,
            },
            {
              id: 153,
              name: '半导体组',
              parentId: 85,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 4,
              seq: 13.0,
              enabled: 1,
            },
            {
              id: 154,
              name: '军工组',
              parentId: 85,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 4,
              seq: 14.0,
              enabled: 1,
            },
            {
              id: 155,
              name: '新能源组',
              parentId: 85,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 4,
              seq: 15.0,
              enabled: 1,
            },
            {
              id: 161,
              name: '科技空间组',
              parentId: 85,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 4,
              seq: 15.0,
              enabled: 1,
            },
            {
              id: 146,
              name: '培训与活动部',
              parentId: 85,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 4,
              seq: 21.0,
              enabled: 1,
            },
            {
              id: 147,
              name: '高端人才猎聘部',
              parentId: 85,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 4,
              seq: 22.0,
              enabled: 1,
            },
            {
              id: 90,
              name: '投行部',
              parentId: 85,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 4,
              seq: 23.0,
              enabled: 1,
            },
            {
              id: 89,
              name: '品牌营销部',
              parentId: 85,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 4,
              seq: 24.0,
              enabled: 1,
            },
            {
              id: 91,
              name: '政策咨询部',
              parentId: 85,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 4,
              seq: 25.0,
              enabled: 1,
            },
          ],
          expanded: false,
          leaf: false,
          checked: null,
          level: 3,
          seq: 2.5,
          enabled: 1,
        },
        {
          id: 137,
          name: '先导院',
          parentId: 1,
          children: [
            {
              id: 138,
              name: '先导院',
              parentId: 137,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 1.0,
              enabled: 1,
            },
          ],
          expanded: false,
          leaf: false,
          checked: null,
          level: 2,
          seq: 3.0,
          enabled: 1,
        },
        {
          id: 139,
          name: '广州硬科院',
          parentId: 1,
          children: [
            {
              id: 140,
              name: '部门',
              parentId: 139,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 0.0,
              enabled: 1,
            },
          ],
          expanded: false,
          leaf: false,
          checked: null,
          level: 2,
          seq: 4.0,
          enabled: 1,
        },
        {
          id: 141,
          name: '中科天塔',
          parentId: 1,
          children: [
            {
              id: 142,
              name: '总经办',
              parentId: 141,
              children: [],
              expanded: false,
              leaf: true,
              checked: null,
              level: 3,
              seq: 1.0,
              enabled: 1,
            },
          ],
          expanded: false,
          leaf: false,
          checked: null,
          level: 2,
          seq: 100.0,
          enabled: 1,
        },
      ],
      expanded: true,
      leaf: false,
      checked: null,
      level: 1,
      seq: 1.0,
      enabled: 1,
    },
  ],
  msg: null,
  expand: null,
}
